os: Visual Studio 2019
version: 0.1.1.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
    - master

build_script:
  - ps: .\build.ps1

after_build:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "artifacts\coverage.netcoreapp3.1.cobertura.xml"

artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\*.snupkg

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off

deploy:

  - provider: NuGet
    api_key:
      secure: 849h/efCPoqFjRMuteSC26Ao67MgmrTNX5kDuTO92eZq0S8BlKFgt0JRPvke90Oz
    artifact: /.*\.*nupkg/
    skip_symbols: false
    on:
      appveyor_repo_tag: true
